# Dockerfile.nlp
FROM pytorchignite/base:latest

# Ignite NLP dependencies
RUN pip install --upgrade --no-cache-dir "torchtext<0.8" \
                                         transformers \
                                         spacy \
                                         nltk
