# Dockerfile.vision
FROM pytorchignite/base:latest

# Ignite vision dependencies
RUN pip install --upgrade --no-cache-dir albumentations \
                                         image-dataset-viz \
                                         numpy \
                                         opencv-python-headless \
                                         py_config_runner \
                                         clearml
