# Dockerfile.hvd-apex-nlp
FROM pytorchignite/hvd-apex:latest

# Ignite NLP dependencies
RUN pip install --upgrade --no-cache-dir "torchtext<0.8" \
                                         transformers \
                                         spacy \
                                         nltk
