# Dockerfile.hvd-nlp
FROM pytorchignite/hvd-base:latest

# Ignite NLP dependencies
RUN pip install --upgrade --no-cache-dir "torchtext<0.10.1" \
                                         transformers \
                                         spacy \
                                         nltk
