# Dockerfile.hvd-nlp
FROM pytorchignite/hvd-base:latest

# Ignite NLP dependencies
RUN pip install --upgrade --no-cache-dir torchtext \
                                         transformers \
                                         spacy \
                                         nltk
