FROM pytorch/pytorch:latest

RUN apt-get update && apt-get install -y --no-install-recommends \
         git && \
     rm -rf /var/lib/apt/lists/*

# install Ignite and "examples" requirements
RUN conda install ignite -c pytorch && \
    conda install -y pillow tensorboard tqdm && \
    conda install -y -c conda-forge opencv albumentations && \
    conda install -y -c vfdev-5 image_dataset_viz && \
    conda clean -ya

# install py-config-runner from pip
RUN pip --no-cache-dir install py-config-runner

ENTRYPOINT ["/bin/sh"]