# Dockerfile.msdp-apex-nlp
FROM pytorchignite/msdp-apex-base:latest

# Ignite NLP dependencies
RUN pip install --upgrade --no-cache-dir torchtext \
                                         transformers \
                                         spacy \
                                         nltk
