# Dockerfile.msdp-nlp
FROM pytorchignite/msdp-base:latest

# Ignite NLP dependencies
RUN pip install --upgrade --no-cache-dir torchtext \
                                         transformers \
                                         spacy \
                                         nltk

ENTRYPOINT ["/bin/bash"]
