# Dockerfile.msdp-apex-nlp
FROM pytorchignite/msdp-apex:latest

# Ignite NLP dependencies
RUN pip install --upgrade --no-cache-dir transformers \
                                         spacy \
                                         nltk \
                                         torchtext
