{% set data = load_setup_py_data() %}

package:
  name: ignite
  version: {{ data['version'] }}

source:
  path: ..

build:
  number: 0
  noarch: python
  script: python -m pip install . -vv

# https://conda.io/docs/user-guide/tasks/build-packages/define-metadata.html#export-runtime-requirements
requirements:
  build:
    - hatch
    - pip
    - python >=3.9
    - pytorch >=1.10
    - setuptools

  run:
    - python >=3.9
    - pytorch >=1.10

test:
  imports:
    - ignite
    - ignite.engine
    - ignite.handlers
    - ignite.metrics
    - ignite.contrib

about:
  home: {{ data['url'] }}
  license: {{ data['license'] }}
  summary: {{ data['description'] }}
