{% set data = load_setup_py_data() %}

package:
  name: ignite
  version: {{ data['version'] }}

source:
  path: ..

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

# https://conda.io/docs/user-guide/tasks/build-packages/define-metadata.html#export-runtime-requirements
requirements:
  build:
    - python
    - setuptools
    - pytorch
    - enum34 # [py < 34]

  run:
    - python
    - pytorch
    - enum34 # [py < 34]

test:
  imports:
    - ignite
    - ignite.engine
    - ignite.handlers
    - ignite.metrics
    - ignite.contrib

about:
  home: {{ data['url'] }}
  license: {{ data['license'] }}
  summary: {{ data['description'] }}
