name: Format python code
on: push
jobs:
  autoblack:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: autoblack
      uses: lgeiger/black-action@v1.0.1
      with:
        args: "."
    - name: Commit and push changes
      uses: stefanzweifel/git-auto-commit-action@v2.0.0
      with:
        commit_author_email: ''
        commit_author_name: AutoBlack
        commit_message: autoblack fix
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
