name: Build And Publish Docker Images

on:
  push:
    branches:
      - master
    paths:
      - docker/**
      - ".github/workflows/docker-publish.yml"
  release:
    types: [published]
  pull_request:
    paths:
      - docker/**
      - ".github/workflows/docker-publish.yml"

jobs:
  build-publish:
    name: Build and Push Docker images to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Trigger Circle-CI pipeline
        env:
          CIRCLE_TOKEN: ${{ secrets.CIRCLE_TOKEN }}
        run: |
          if [ $GITHUB_EVENT_NAME == 'pull_request' ]; then should_publish_docker_images=false; else should_publish_docker_images=true; fi
          branch=$GITHUB_REF
          sh .github/workflows/trigger_circle_ci.sh $should_publish_docker_images $branch
