name: Trigger Build And Publish Docker Images

on:
  push:
    branches:
      - master
    paths:
      - docker/**
      - ".github/workflows/docker-publish.yml"

jobs:
  build-publish:
    name: Trigger Build and Push Docker images to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      # TODO
