name: Build And Publish Docker Images

on:
  push:
    branches:
      - master
    paths:
      - docker/**
      - '.github/workflows/docker-publish.yml'
  release:
    types: [published]
  pull_request:
    paths:
      - docker/**
      - '.github/workflows/docker-publish.yml'

jobs:
  build-publish:
    name: Build and Push Docker images to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build all Horovod flavoured PyTorch-Ignite images
        working-directory: ./docker
        run: |
          chmod +x ./hvd/build_all.sh
          ./hvd/build_all.sh

      - name: Build all PyTorch-Ignite images
        working-directory: ./docker
        run: |
          chmod +x ./main/build_all.sh
          ./main/build_all.sh
      - name: Build all MS DeepSpeed flavoured PyTorch-Ignite images
        working-directory: ./docker
        run: |
          chmod +x ./msdp/build_all.sh
          ./msdp/build_all.sh

      - name: List built images
        working-directory: ./docker
        run: docker images | grep pytorchignite

      - name: Push all PyTorch-Ignite Docker images
        if: github.event_name == 'push'
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
        working-directory: ./docker
        run: |
          chmod +x ./push_all.sh
          ./push_all.sh
