name: Stable Releases

on:
  push:
    branches:
      - master
    paths:
      - docker/**
      - ".github/workflows/release.yml"
  release:
    types: [published]

jobs:
  build-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Miniconda
        if: github.event_name == 'release'
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          python-version: 3.8

      - name: Install dependencies
        if: github.event_name == 'release'
        shell: bash -l {0}
        run: |
          conda install -y pytorch torchvision cpuonly -c pytorch
          pip install -r requirements-dev.txt
          pip install --upgrade --no-cache-dir twine
          python setup.py install

      - name: Build and Publish Conda binaries
        if: github.event_name == 'release'
        shell: bash -l {0}
        env:
          ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
          UPLOAD_USER: "pytorch"
        run: |
          chmod +x ./conda.recipe/build_and_upload.sh
          ./conda.recipe/build_and_upload.sh

      - name: Build and Publish PyPI binaries
        if: github.event_name == 'release'
        shell: bash -l {0}
        run: |
          python setup.py sdist bdist_wheel
          twine check dist/*
          TWINE_USERNAME="${{ secrets.PYPI_USER }}" TWINE_PASSWORD="${{ secrets.PYPI_TOKEN }}" twine upload --verbose dist/*

      - name: Build And Publish Docker Images
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Trigger Circle-CI pipeline
        env:
          CIRCLE_TOKEN: ${{ secrets.CIRCLE_TOKEN }}
        run: |
          pip install requests

          if [ $GITHUB_EVENT_NAME == 'pull_request' ]; then should_publish_docker_images=false; else should_publish_docker_images=true; fi
          branch=$GITHUB_REF

          python -u .github/workflows/trigger_circle_ci.py $should_publish_docker_images $branch
