name: Anaconda Stable Releases

on:
  release:
    types: [published]

jobs:
  conda-build-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@be893c923ea9cf1cf7cd510fbdde27c7e18cbdcb # v4.1.0
        with:
          miniconda-version: "latest"
          python-version: "3.13"

      - name: Build and Publish Conda binaries
        shell: bash -l {0}
        env:
          ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
          UPLOAD_USER: "pytorch"
        run: |
          chmod +x ./conda.recipe/build_and_upload.sh
          ./conda.recipe/build_and_upload.sh
