name: PyPI Stable Releases

on:
  release:
    types: [published]

jobs:
  build-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup uv
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
        with:
          version: "latest"
          python-version: "3.13"
          activate-environment: true

      - name: Install dependencies
        run: |
          uv pip install torch torchvision --index-url https://download.pytorch.org/whl/cpu
          uv pip install -r requirements-dev.txt

      - name: Build and Publish PyPI binaries
        run: |
          # workaround to fix https://github.com/pytorch/ignite/issues/2373
          uv pip uninstall -y twine pkginfo
          uv pip install --upgrade --no-cache-dir hatch twine 'pkginfo>=1.8.2'
          hatch build
          twine --version
          twine check dist/*
          TWINE_USERNAME="${{ secrets.PYPI_USER }}" TWINE_PASSWORD="${{ secrets.PYPI_TOKEN }}" twine upload --verbose dist/*
