name: PyPI Stable Releases

on:
  release:
    types: [published]

jobs:
  build-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup uv
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
        with:
          version: "latest"
          python-version: "3.13"
          activate-environment: true

      - name: Install dependencies
        run: |
          uv pip install torch torchvision --index-url https://download.pytorch.org/whl/cpu
          uv pip install -r requirements-dev.txt

      - name: Build and Publish PyPI binaries
        run: |
          # workaround to fix https://github.com/pytorch/ignite/issues/2373
          uv pip uninstall -y twine pkginfo
          uv pip install --upgrade --no-cache-dir hatch twine 'pkginfo>=1.8.2'
          hatch build
          twine --version
          twine check dist/*
          TWINE_USERNAME="${{ secrets.PYPI_USER }}" TWINE_PASSWORD="${{ secrets.PYPI_TOKEN }}" twine upload --verbose dist/*
