name: Anaconda Stable Releases

on:
  release:
    types: [published]

jobs:
  conda-build-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@8ee1f361103df19b6f8c8655fd3967a8ecb162d5 # v4.0.1
        with:
          miniconda-version: "latest"
          python-version: "3.13"

      - name: Build and Publish Conda binaries
        shell: bash -l {0}
        env:
          ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
          UPLOAD_USER: "pytorch"
        run: |
          chmod +x ./conda.recipe/build_and_upload.sh
          ./conda.recipe/build_and_upload.sh
